app/models.py
from app import db,login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy




db=SQLAlchemy()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20))
    email = db.Column(db.String(255))
    posts = db.relationship('Post', backref = 'user', lazy = 'dynamic' )
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

   

    def save_user(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'{self.username}'

class Post(db.Model):

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key = True)
    post = db.Column(db.String(99999))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    title = db.Column(db.String(255))
    author = db.Column(db.String(255))
    date = db.Column(db.DateTime, default = datetime.utcnow)

    

    
    def save_post(self):
        db.session.add(self)
        db.session.commit()

    

    def delete_post(self):

        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'{self.id}'


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key=True)
    post_id = db.Column(db.Integer,db.ForeignKey('posts.id'),nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    comment = db.Column(db.Text(),nullable=False)


    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post_id):
        comments = Comment.query.filter_by(post_id=post_id).all()
        return comments

    def __repr__(self):
        return f'comment:{self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, InputRequired
from app.models import Post

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    post = StringField('Post', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_title(self, title):
        post = Post.query.filter_by(title=title.data).first()
        if post:
            raise ValidationError('Title already exists. Please choose a different title.')

    def validate_author(self, author):
        post = Post.query.filter_by(author=author.data).first()
        if post:
            raise ValidationError('Author already exists. Please choose a different author.')

    def validate_post(self, post):
        post = Post.query.filter_by(post=post.data).first()
        if post:
            raise ValidationError('Post already exists. Please choose a different post.')


class CommentForm(FlaskForm):
    title = StringField('Comment title')
    comment = TextAreaField('Blog comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


db = SQLAlchemy()
bootstrap = Bootstrap()

def create_app(config_name):

    app = Flask(__name__)

    # Import configuration settings

    app.config.from_object(config_options[config_name])

    # Register blueprints

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    

    # Initialize extensions

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, flash, redirect, url_for, request
from app.main.forms import PostForm
from app.models import Post, User, Comment 
from . import main
from .forms import CommentForm, PostForm
from flask_login import login_required, current_user
from app import db

@main.route('/')
def index():
    
    return render_template('home.html')

@main.route('/home')
def home():
    posts = Post.query.all()
    
    return render_template('home.html', posts = posts)


@main.route('/post', methods=['GET', 'POST'])
def post():
    title = 'Post Form'
    postform = PostForm()
    if postform.validate_on_submit():
        post = Post(title=postform.title.data, author=postform.author.data, post=postform.post.data)
        post.save_post()


        flash('Post created!')
        return redirect(url_for('main.home'))



    return render_template('post.html',title=title, postform=postform)






@main.route('/comment/<int:post_id>', methods = ['GET','POST'])
@login_required
def new_comment(post_id):
    form = CommentForm()
    post =Post.query.get(post_id)
    all_comments = Comment.query.filter_by(post_id = post_id).all()
    if form.validate_on_submit():
        title = form.title.data
        comment = form.comment.data
        post_id = post_id
        user_id = current_user._get_current_object().id
        # Updated comment instance
        new_comment= Comment(title=title,post_comment=comment,user_id=user_id,post_id=post_id)

        # save review method
        new_comment.save_comment()
        return redirect(url_for('.new_comment',pitch_id = post_id))
    return render_template('new_comment.html',post=post,all_comments=all_comments,comment_form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    

    return render_template("profile/profile.html", user = user)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block styles%}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock  %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    

    <title>MyBlogs</title>


</head>
<header>
    {% block navbar %}
    {% include "navbar.html" %}
    {% endblock %}

</header>


<body>
  
    
    {% block content %}
    {% endblock %}


</body>

</html>

app/templates/home.html
{% extends "base.html" %}

{% block content %}

<h1 style="color: white;">MyBlog</h1>
<h2 style="color:white">A place where you can create and view great blogs.</h2>

<div class="card" style="width: 18rem;">
    
    <div class="card-body">
        <h5 style="color:white" ="card-title">Top Blogs</h5>
        <p style="color: white;" class="card-text">Investments in nature conservation have long been neglected, and as a result, nature across Europe is now in a terrible
        state. Biodiversity conservation projects can address this by providing cost-effective ways to restore nature and
        sustainably manage ecosystems; tackle climate change; and deliver environmental, social and economic benefits at the
        same time.</p>
        <a href="#" class="btn btn-primary">Comment</a>
    </div>
</div>

<a style="font-size: 6vh;" href="{{url_for('main.post')}}">Create Post Here</a>
<div class="container-fluid">
    <div class="container">
       

            <div class="row">
                {% for post in posts %}
                <div class="col-sm-4">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{post.post}}</p>
                            <a href="#" class="btn btn-primary">{{post.title}}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        
    </div>
    </div>








    {% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> MyBlog </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('auth.login')}}">Login</a></li>
                <li><a href="{{url_for('auth.register')}}">Register</a></li>
        </div>

    </div>
</div>

app/templates/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<div class="container">
    <div class="row" align="center">
        <div class="col-md-4">

            {{ wtf.quick_form(postform) }}
            

        </div>
    </div>
</div>

{% endblock %}